version: 2

services:
  mysql-tcp:
    connector: mysql
    listenOn: tcp://0.0.0.0:13306
    credentials:
      username:
        from: conjur
        get: conjur/xa-secretless-db/mysql/username
      password:
        from: conjur
        get: conjur/xa-secretless-db/mysql/password
      host:
        from: conjur
        get: conjur/xa-secretless-db/mysql/hostname
      port:
        from: conjur
        get: conjur/xa-secretless-db/mysql/port

  mysql-sock:
    connector: mysql
    listenOn: unix:///sock/mysql
    credentials:
      username:
        from: conjur
        get: conjur/xa-secretless-db/mysql/username
      password:
        from: conjur
        get: conjur/xa-secretless-db/mysql/password
      host:
        from: conjur
        get: conjur/xa-secretless-db/mysql/hostname
      port:
        from: conjur
        get: conjur/xa-secretless-db/mysql/port

  pg-tcp:
    connector: pg
    listenOn: tcp://0.0.0.0:15432
    credentials:
      username:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/username
      password:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/password
      host:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/hostname
      port:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/port

  pg-sock:
    connector: pg
    listenOn: unix:///sock/.s.PGSQL.5432
    credentials:
      username:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/username
      password:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/password
      host:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/hostname
      port:
        from: conjur
        get: conjur/xa-secretless-db/postgresql/port

  mssql-tcp:
    connector: mssql
    listenOn: tcp://0.0.0.0:11433
    credentials:
      username:
        from: conjur
        get: conjur/xa-secretless-mssql-db/mssql/username
      password:
        from: conjur
        get: conjur/xa-secretless-mssql-db/mssql/password
      host:
        from: conjur
        get: conjur/xa-secretless-mssql-db/mssql/hostname
      port:
        from: conjur
        get: conjur/xa-secretless-mssql-db/mssql/port
