common:
  KUBECTL_CLI_URL: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
  OPENSHIFT_CLI_URL: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz

  CONJUR_ACCOUNT: my-account
  CONJUR_ADMIN_PASSWORD: ADmin123!!!!

  GCLOUD_CLUSTER_NAME: ""
  GCLOUD_ZONE: ""
  GCLOUD_PROJECT_NAME: ""
  GCLOUD_SERVICE_KEY: ""

  OPENSHIFT_URL: ""
  OPENSHIFT_VERSION: ""
  OPENSHIFT_USERNAME: ""
  OPENSHIFT_PASSWORD: ""

gke:
  GCLOUD_CLUSTER_NAME: !var ci/gke/rapid/cluster-name
  GCLOUD_ZONE: !var ci/gke/zone
  GCLOUD_PROJECT_NAME: !var ci/gke/project-name
  GCLOUD_SERVICE_KEY: !var:file ci/gke/service-key

  PLATFORM: kubernetes
  TEST_PLATFORM: gke
  DOCKER_REGISTRY_URL: us.gcr.io
  DOCKER_REGISTRY_PATH: us.gcr.io/refreshing-mark-284016
  PULL_DOCKER_REGISTRY_URL: us.gcr.io
  PULL_DOCKER_REGISTRY_PATH: us.gcr.io/refreshing-mark-284016

oc311:
  OPENSHIFT_VERSION: "3.11"
  OPENSHIFT_URL: !var ci/openshift/3.11/hostname
  OPENSHIFT_USERNAME: !var ci/openshift/3.11/username
  OPENSHIFT_PASSWORD: !var ci/openshift/3.11/password

  PLATFORM: openshift
  TEST_PLATFORM: openshift311
  DOCKER_REGISTRY_URL: !var ci/openshift/3.11/registry-url
  DOCKER_REGISTRY_PATH: !var ci/openshift/3.11/registry-url
  PULL_DOCKER_REGISTRY_URL: !var ci/openshift/3.11/registry-url
  PULL_DOCKER_REGISTRY_PATH: !var ci/openshift/3.11/registry-url

oldest:
  OPENSHIFT_VERSION: !var ci/openshift/oldest/version
  OPENSHIFT_URL: !var ci/openshift/oldest/hostname
  OPENSHIFT_USERNAME: !var ci/openshift/oldest/username
  OPENSHIFT_PASSWORD: !var ci/openshift/oldest/password

  PLATFORM: openshift
  TEST_PLATFORM: openshift
  DOCKER_REGISTRY_URL: !var ci/openshift/oldest/registry-url
  DOCKER_REGISTRY_PATH: !var ci/openshift/oldest/registry-url
  PULL_DOCKER_REGISTRY_URL: !var ci/openshift/oldest/registry-url
  PULL_DOCKER_REGISTRY_PATH: !var ci/openshift/oldest/registry-url

current:
  OPENSHIFT_VERSION: !var ci/openshift/current/version
  OPENSHIFT_URL: !var ci/openshift/current/api-url
  OPENSHIFT_USERNAME: !var ci/openshift/current/username
  OPENSHIFT_PASSWORD: !var ci/openshift/current/password
  OSHIFT_CLUSTER_ADMIN_USERNAME: !var ci/openshift/current/username
  OSHIFT_CONJUR_ADMIN_USERNAME: !var ci/openshift/current/username

  PLATFORM: openshift
  TEST_PLATFORM: openshift
  DOCKER_REGISTRY_URL: !var ci/openshift/current/registry-url
  DOCKER_REGISTRY_PATH: !var ci/openshift/current/registry-url
  PULL_DOCKER_REGISTRY_URL: !var ci/openshift/current/internal-registry-url
  PULL_DOCKER_REGISTRY_PATH: !var ci/openshift/current/internal-registry-url

next:
  OPENSHIFT_CLI_URL: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.8.2/openshift-client-linux.tar.gz
  OPENSHIFT_VERSION: !var ci/openshift/next/version
  OPENSHIFT_URL: !var ci/openshift/next/api-url
  OPENSHIFT_USERNAME: !var ci/openshift/next/username
  OPENSHIFT_PASSWORD: !var ci/openshift/next/password
  OSHIFT_CLUSTER_ADMIN_USERNAME: !var ci/openshift/next/username
  OSHIFT_CONJUR_ADMIN_USERNAME: !var ci/openshift/next/username

  PLATFORM: openshift
  TEST_PLATFORM: openshift
  DOCKER_REGISTRY_URL: !var ci/openshift/next/registry-url
  DOCKER_REGISTRY_PATH: !var ci/openshift/next/registry-url
  PULL_DOCKER_REGISTRY_URL: !var ci/openshift/next/internal-registry-url
  PULL_DOCKER_REGISTRY_PATH: !var ci/openshift/next/internal-registry-url
