name: Helm Tests

on:
  # Run this on pushes to main
  push:
    branches:
    - main

  # Or when PR operations are done
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  validate-test-helm-v3:
    name: Validate Helm tests with Helm V3 on a KinD Cluster
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kube-tag:
          - v1.18.2
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.3.0

      - name: Run cluster prep Helm chart tests
        run: ./bin/validate-helm -c -C cluster_prep

      - name: Run Namespace prep Helm chart tests
        run: ./bin/validate-helm -C namespace_prep
